In [16]:
import pandas as pd
import os

In [17]:
#read the path 
file_path = "data/raw_ufo_data"

In [18]:
# list all the files from the directory
file_list = os.listdir(file_path)

In [20]:
df = pd.concat([pd.read_csv(file_path + '/' + f) for f in file_list], ignore_index=True)
df

,Date / Time,City,State,Country,Shape,Duration,Summary,Posted,Images
0,9/30/21 22:50,Ocala,FL,USA,NaN,45 seconds,Object traveling across the sky with two disti...,10/19/21,NaN
1,9/30/21 22:49,Atlanta,GA,USA,Fireball,2 minutes,Maybe a meteor?,10/19/21,NaN
2,9/30/21 21:45,Lakeland,GA,USA,Other,60 seconds,Straight light 60 foot long witness two police,10/19/21,NaN
3,9/30/21 21:25,Grand Haven,MI,USA,Light,01:00,"Single, Bright Object moving like a Heartbeat ...",10/19/21,NaN
4,9/30/21 20:59,Lewis Center,OH,USA,Triangle,5 minutes,Traveling east on Lewis Center Rd I spotted wh...,10/19/21,NaN
...,...,...,...,...,...,...,...,...,...
14441,2/1/21 18:50,Frisco,TX,USA,Light,1-2 min,4 orange glowing lights flying in single row f...,3/2/21,NaN
14442,2/1/21 17:02,Jonesboro,AR,USA,NaN,NaN,MADAR Node 143,3/2/21,NaN
14443,2/1/21 15:36,Springfield,MO,USA,NaN,NaN,MADAR Node 36,3/2/21,NaN
14444,2/1/21 15:25,Elizabeth,CO,USA,NaN,NaN,MADAR Node 34,3/2/21,NaN
14445,2/1/21 09:00,Colorado Springs,CO,USA,Teardrop,1 hour ongoing,8 ufo in the sky - looked like balloons but no...,3/2/21,NaN

In [21]:
output_path = 'data/cleaned_ufo_data/data_combined.csv'

# append all files together
df.to_csv(output_path, index=False)