In [11]:
import pandas as pd
import os

In [17]:
#read the path 
file_path = "C:cmpt353project/ufo_data/"

In [9]:
# list all the files from the directory
file_list = os.listdir(file_path)

In [18]:
file_list

['202001.csv',
 '202002.csv',
 '202003.csv',
 '202004.csv',
 '202005.csv',
 '202006.csv',
 '202007.csv',
 '202008.csv',
 '202009.csv',
 '202010.csv',
 '202011.csv',
 '202012.csv',
 '202101.csv',
 '202102.csv',
 '202103.csv',
 '202104.csv',
 '202105.csv',
 '202106.csv',
 '202107.csv',
 '202108.csv',
 '202109.csv',
 '202110.csv',
 '202111.csv',
 '202112.csv',
 '202201.csv',
 '202202.csv',
 '202203.csv',
 '202204.csv',
 '202205.csv',
 '202206.csv',
 '202207.csv',
 '202208.csv',
 '202209.csv',
 '202210.csv']

In [21]:
df = pd.concat([pd.read_csv("ufo_data/" + f) for f in file_list], ignore_index=True)

In [23]:
df

,Date / Time,City,State,Country,Shape,Duration,Summary,Posted,Images
0,1/31/20 21:30,Prospect,OR,USA,Light,30 minute,1.31.2020 Approximately 9:30-10 While driving ...,2/7/20,NaN
1,1/31/20 19:57,Arizona City,AZ,USA,Unknown,2:55,Blinking lights tha pull away and tilt.,5/1/20,NaN
2,1/31/20 19:56,Arizona City,AZ,USA,Unknown,2,Blinking unexplained lights that tilt and move.,2/25/20,NaN
3,1/31/20 19:30,Sevierville,TN,USA,Oval,3-5 minutes,This is twice in one week I've seen this. Roun...,2/7/20,NaN
4,1/31/20 18:45,Cornelius,OR,USA,NaN,NaN,5 bright orange lights traveling in drunken ma...,2/7/20,NaN
...,...,...,...,...,...,...,...,...,...
14441,10/1/22 15:34,Huntsville,AL,USA,Cigar,2 - 3 minutes,Cigar shaped with a bright circular light to t...,10/8/22,Yes
14442,10/1/22 11:50,Gulf breeze,FL,USA,Circle,Seconds intermittent,This was circular and was blur...I've never se...,10/8/22,NaN
14443,10/1/22 09:52,Redwood valley,CA,USA,Other,NaN,A very very large huge X flying in and out of ...,10/8/22,NaN
14444,10/1/22 04:30,Bountiful,UT,USA,Light,45 seconds,deep above maybe outer space,10/8/22,NaN
14445,10/1/22 03:05,Columbus,MS,USA,Light,~15 seconds to a minute,BRIGHT light panned like a spotlight in both w...,10/8/22,NaN

In [22]:
# append all files together
df.to_csv('data_combined.csv')